apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nodejs-staging

resources:
- ../../base

patchesStrategicMerge:
- replica-patch.yaml

namePrefix: staging-

commonLabels:
  environment: staging