apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nodejs-canary

resources:
- ../../base

namePrefix: canary-

commonLabels:
  stage: promote-canary
  version: canary

patchesStrategicMerge:
- replica-patch.yaml