apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app-v2
  namespace: sample-app-v2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-app-v2
  template:
    metadata:
      labels:
        app: nodejs-app-v2
    spec:
      containers:
        - name: nodejs-app-v2
          image: nginx:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-app-v2-service
  namespace: sample-app-v2
spec:
  selector:
    app: nodejs-app-v2
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
