replicaCount: 2

image:
  repository: "nginx"
  tag: "1.23"
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

namespace:
  create: true
  name: sample-app-helm

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}