apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nodejs-prod

resources:
- ../../base

patchesStrategicMerge:
- replica-patch.yaml

namePrefix: prod-

commonLabels:
  environment: production

images:
- name: nginx
  newName: nginx
  newTag: "1.23"
