apiVersion: v1
kind: Service
metadata:
  name: {{ include "nodejs-app.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ include "nodejs-app.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 80
    protocol: TCP
  selector:
    app: {{ include "nodejs-app.name" . }}