apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nodejs-canary

resources:
- ../../base

namePrefix: deploy-

commonLabels:
  stage: deploy
  version: canary

patchesStrategicMerge:
- replica-patch.yaml